# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.put_api_v4_broadcast_messages_id_request import PutApiV4BroadcastMessagesIdRequest

class TestPutApiV4BroadcastMessagesIdRequest(unittest.TestCase):
    """PutApiV4BroadcastMessagesIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutApiV4BroadcastMessagesIdRequest:
        """Test PutApiV4BroadcastMessagesIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutApiV4BroadcastMessagesIdRequest`
        """
        model = PutApiV4BroadcastMessagesIdRequest()
        if include_optional:
            return PutApiV4BroadcastMessagesIdRequest(
                message = '',
                starts_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                color = '',
                font = '',
                target_access_levels = [
                    10
                    ],
                target_path = '',
                broadcast_type = 'banner',
                dismissable = True
            )
        else:
            return PutApiV4BroadcastMessagesIdRequest(
        )
        """

    def testPutApiV4BroadcastMessagesIdRequest(self):
        """Test PutApiV4BroadcastMessagesIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
