# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_entities_plan_limit import APIEntitiesPlanLimit

class TestAPIEntitiesPlanLimit(unittest.TestCase):
    """APIEntitiesPlanLimit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIEntitiesPlanLimit:
        """Test APIEntitiesPlanLimit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIEntitiesPlanLimit`
        """
        model = APIEntitiesPlanLimit()
        if include_optional:
            return APIEntitiesPlanLimit(
                ci_pipeline_size = 0,
                ci_active_jobs = 0,
                ci_project_subscriptions = 2,
                ci_pipeline_schedules = 10,
                ci_needs_size_limit = 50,
                ci_registered_group_runners = 1000,
                ci_registered_project_runners = 1000,
                conan_max_file_size = 3221225472,
                enforcement_limit = 15000,
                generic_packages_max_file_size = 5368709120,
                helm_max_file_size = 5242880,
                limits_history = {"enforcement_limit"=>[{"timestamp"=>1686909124, "user_id"=>1, "username"=>"x", "value"=>5}],
                   "notification_limit"=>[{"timestamp"=>1686909124, "user_id"=>2, "username"=>"y", "value"=>7}]},
                maven_max_file_size = 3221225472,
                notification_limit = 15000,
                npm_max_file_size = 524288000,
                nuget_max_file_size = 524288000,
                pipeline_hierarchy_size = 1000,
                pypi_max_file_size = 3221225472,
                terraform_module_max_file_size = 1073741824,
                storage_size_limit = 15000
            )
        else:
            return APIEntitiesPlanLimit(
        )
        """

    def testAPIEntitiesPlanLimit(self):
        """Test APIEntitiesPlanLimit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
