# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class APIEntitiesCommit(BaseModel):
    """
    APIEntitiesCommit
    """ # noqa: E501
    id: Optional[StrictStr] = None
    short_id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    parent_ids: Optional[List[StrictStr]] = None
    title: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    author_name: Optional[StrictStr] = None
    author_email: Optional[StrictStr] = None
    authored_date: Optional[datetime] = None
    committer_name: Optional[StrictStr] = None
    committer_email: Optional[StrictStr] = None
    committed_date: Optional[datetime] = None
    trailers: Optional[Dict[str, Any]] = None
    web_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "short_id", "created_at", "parent_ids", "title", "message", "author_name", "author_email", "authored_date", "committer_name", "committer_email", "committed_date", "trailers", "web_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIEntitiesCommit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIEntitiesCommit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "short_id": obj.get("short_id"),
            "created_at": obj.get("created_at"),
            "parent_ids": obj.get("parent_ids"),
            "title": obj.get("title"),
            "message": obj.get("message"),
            "author_name": obj.get("author_name"),
            "author_email": obj.get("author_email"),
            "authored_date": obj.get("authored_date"),
            "committer_name": obj.get("committer_name"),
            "committer_email": obj.get("committer_email"),
            "committed_date": obj.get("committed_date"),
            "trailers": obj.get("trailers"),
            "web_url": obj.get("web_url")
        })
        return _obj


